source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JJJUtils_Example', :exclusive => true do
  pod "JJJUtils", :path => "../"
end

target 'JJJUtils_Tests', :exclusive => true do
  pod "JJJUtils", :path => "../"
end
